config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bash_logout:
    src: bash_logout
    dst: ~/.bash_logout
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
    chmod: '664'
  f_bashrc_custom:
    src: bashrc_custom
    dst: ~/.bashrc_custom
    chmod: '664'
  d_compton:
    src: config/compton
    dst: ~/.config/compton
  d_fontconfig:
    src: config/fontconfig
    dst: ~/.config/fontconfig
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_i3status:
    src: config/i3status
    dst: ~/.config/i3status
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_fonts:
    src: fonts
    dst: ~/.fonts
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config:
    src: ssh/config
    dst: ~/.ssh/config
    chmod: '600'
  d_tmux:
    src: tmux
    dst: ~/.tmux
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_copyq.conf:
    src: config/copyq/copyq.conf
    dst: ~/.config/copyq/copyq.conf
  f_zshrc_oeken:
    src: zshrc_oeken
    dst: ~/.zshrc_oeken
    chmod: '664'
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
    chmod: '664'
profiles:
  celonis-lp-516:
    dotfiles:
    - f_zshrc
    - f_bash_logout
    - f_bashrc
    - f_bash_aliases
    - f_bashrc_custom
    - d_compton
    - d_fontconfig
    - d_i3
    - d_i3status
    - d_picom
    - d_rofi
    - d_fonts
    - f_gitconfig
    - f_config
    - d_tmux
    - f_tmux.conf
    - f_xmodmap
    - f_copyq.conf
    - f_zshrc_oeken
    - f_gitignore
